export const CALL_API_GET_CATEGORY = "CALL_API_GET_CATEGORY";
export const HANDLE_INPUT = "HANDLE_INPUT";
export const HANDLE_INPUT_OPTION = "HANDLE_INPUT_OPTION";
export const CALL_API_CREATE_POST = "CALL_API_CREATE_POST";
export const CALL_API_GET_POST = "CALL_API_GET_POST";
export const CALL_API_DELE_POST = "CALL_API_DELE_POST";
export const HANDLE_FILE_INPUT = "HANDLE_FILE_INPUT";
export const HANDLE_POST_CONTENT = "HANDLE_POST_CONTENT";