export const CALL_API_GET_CATEGORY = "CALL_API_GET_CATEGORY";
export const HANDLE_INPUT = "HANDLE_INPUT";
export const HANDLE_INPUT_OPTION = "HANDLE_INPUT_OPTION";
export const CALL_API_CREATE_POST = "CALL_API_CREATE_POST";
